# Generated by Django 5.1 on 2024-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0004_product_image_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
